#!/bin/bash

echo "Running git pre-commit hook"


echo "Grant execute permission for gradlew"
chmod +x ./gradlew

echo "
===================
|  Formatting code with ktlintFormat...
===================
"

./gradlew ktlintFormat

echo "
===================
|  Running ktlintCheck...
===================
"

./gradlew ktlintCheck

ktlintCheckStatus=$?

if [[ $ktlintCheckStatus -ne 0 ]]; then
    exit 1
else
    exit 0
fi