#!/bin/bash

echo "Running git pre-commit hook"


echo "
===================
|  Formatting code with ktlintFormat...
===================
"

./gradlew ktlintCheck

echo "
===================
|  Running ktlintCheck...
===================
"

./gradlew ktlintCheck

ktlintCheckStatus=$?

if [[ $ktlintCheckStatus -ne 0 ]]; then
    exit 1
else
    exit 0
fi