#!/bin/bash

echo "Running git pre-commit hook"

#export JAVA_HOME="C:\Program Files\Java\jdk-22"  # Replace with your JDK path
#export PATH="$JAVA_HOME/bin:$PATH"


echo "Grant execute permission for gradlew"
chmod +x ./gradlew

echo "
===================
|  Formatting code with ktlintFormat...
===================
"

./gradlew ktlintCheck

echo "
===================
|  Running ktlintCheck...
===================
"

./gradlew ktlintCheck

ktlintCheckStatus=$?

if [[ $ktlintCheckStatus -ne 0 ]]; then
    exit 1
else
    exit 0
fi